baseURL = "/"
languageCode = "en-us"
title = "MechaGM"
author = "Parker Harris Emerson"
theme = "story"

[params]
    author = "Parker Harris Emerson"
    
[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"